### ISSUE TITLE
Verlinkung eures Beitrages im Haupt-Repository?

### ISSUE THREAD

**Issue by jonico** [MarkL4YG/informaticup-2020#2]
Hallo @MarkL4YG,

bis jetzt haben wir eure tolle Einsendung noch nicht in https://github.com/informatiCup/informatiCup2020/tree/master/github-sonderpreis gesehen, wollt ihr einen pull-request stellen?

Liebe Grüße und frohe Ostern

@jonico

:octocat: ❤️

**Comment by MarkTwoFive** [comment]
Moin @jonico ,
können wir gerne machen :slightly_smiling_face: 
Danke für die Nachfrage!

Liebe Grüße und gleichfalls :)
